services:
  - type: web
    name: unipod-todo
    runtime: docker
    plan: starter
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://unipod-todo.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: APP_LOCALE
        value: en
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: array
      - key: QUEUE_CONNECTION
        value: sync
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
    autoDeploy: true

databases:
  - name: unipod-db
    plan: starter
    databaseName: unipod
    user: unipod
